import type { Product } from '../domain/index';
export const products: Product[] = [
  {
    id: 'pixel-9',
    slug: 'google-pixel-9-128gb-obsidian',
    name: 'Google Pixel 9',
    brand: 'Google',
    category: 'phones',
    color: 'Obsidian',
    subtitle: '12 GB RAM · 128 GB · Obsidian',
    description:
      'A little more possibility, in your pocket. Compare the exact 128 GB Obsidian variant across two demo sources.',
    attributes: {
      Model: 'Pixel 9',
      RAM: '12 GB',
      Storage: '128 GB',
      Color: 'Obsidian',
      Region: 'India',
      Condition: 'New',
      Display: '6.3-inch OLED',
      Processor: 'Google Tensor G4',
      Pack: '1',
    },
    basePrice: 5499900,
    accent: '#42494c',
  },
  {
    id: 'nothing-3a',
    slug: 'nothing-phone-3a-256gb-white',
    name: 'Nothing Phone (3a)',
    brand: 'Nothing',
    category: 'phones',
    color: 'White',
    subtitle: '8 GB RAM · 256 GB · White',
    description: 'Thoughtful design, everyday capability. An exact-variant demo comparison.',
    attributes: {
      Model: 'Phone (3a)',
      RAM: '8 GB',
      Storage: '256 GB',
      Color: 'White',
      Region: 'India',
      Condition: 'New',
      Display: '6.77-inch AMOLED',
      Processor: 'Snapdragon 7s Gen 3',
      Pack: '1',
    },
    basePrice: 2499900,
    accent: '#deded9',
  },
  {
    id: 'sony-xm5',
    slug: 'sony-wh-1000xm5-black',
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'audio',
    color: 'Black',
    subtitle: 'Wireless · Noise cancelling · Black',
    description:
      'Find your quiet. Compare the same black, single-unit headphones with known delivery charges.',
    attributes: {
      Model: 'WH-1000XM5',
      Color: 'Black',
      Condition: 'New',
      Pack: '1',
      Connectivity: 'Bluetooth',
      Battery: 'Up to 30 hours',
      Type: 'Over-ear',
    },
    basePrice: 2499000,
    accent: '#363839',
  },
  {
    id: 'macbook-air',
    slug: 'macbook-air-m4-16gb-256gb-sky-blue',
    name: 'MacBook Air 13″',
    brand: 'Apple',
    category: 'laptops',
    color: 'Sky Blue',
    subtitle: 'M4 · 16 GB RAM · 256 GB SSD',
    description:
      'Light on your desk. Big on possibilities. This demo compares the 13-inch M4 configuration only.',
    attributes: {
      Model: 'MacBook Air M4',
      RAM: '16 GB',
      Storage: '256 GB',
      Color: 'Sky Blue',
      Condition: 'New',
      Display: '13.6-inch',
      Processor: 'Apple M4',
      GPU: '8-core',
      Pack: '1',
    },
    basePrice: 8999000,
    accent: '#aabdc5',
  },
  {
    id: 'ipad-air',
    slug: 'ipad-air-m3-128gb-blue',
    name: 'iPad Air 11″',
    brand: 'Apple',
    category: 'tablets',
    color: 'Blue',
    subtitle: 'M3 · 128 GB · Wi-Fi · Blue',
    description:
      'A fresh space for your next idea. Wi-Fi and cellular models remain separate variants.',
    attributes: {
      Model: 'iPad Air M3',
      Storage: '128 GB',
      Color: 'Blue',
      Condition: 'New',
      Connectivity: 'Wi-Fi',
      Display: '11-inch',
      Pack: '1',
    },
    basePrice: 5490000,
    accent: '#9fbbca',
  },
  {
    id: 'samsung-s25',
    slug: 'samsung-galaxy-s25-256gb-navy',
    name: 'Samsung Galaxy S25',
    brand: 'Samsung',
    category: 'phones',
    color: 'Navy',
    subtitle: '12 GB RAM · 256 GB · Navy',
    description:
      'A compact flagship. Prices here belong to the India-region Navy 256 GB demo variant.',
    attributes: {
      Model: 'Galaxy S25',
      RAM: '12 GB',
      Storage: '256 GB',
      Color: 'Navy',
      Region: 'India',
      Condition: 'New',
      Display: '6.2-inch AMOLED',
      Processor: 'Snapdragon 8 Elite',
      Pack: '1',
    },
    basePrice: 7099900,
    accent: '#374b65',
  },
  {
    id: 'dell-monitor',
    slug: 'dell-s2722qc-27-4k',
    name: 'Dell 27″ 4K Monitor',
    brand: 'Dell',
    category: 'monitors',
    color: 'Silver',
    subtitle: 'S2722QC · 4K UHD · USB-C',
    description: 'A clearer view of everything. Compare the precise S2722QC 60 Hz configuration.',
    attributes: {
      Model: 'S2722QC',
      Display: '27-inch',
      Resolution: '3840 × 2160',
      Refresh: '60 Hz',
      Color: 'Silver',
      Condition: 'New',
      Pack: '1',
    },
    basePrice: 2799900,
    accent: '#b6b9b7',
  },
  {
    id: 'buds-pro',
    slug: 'nothing-ear-white',
    name: 'Nothing Ear',
    brand: 'Nothing',
    category: 'audio',
    color: 'White',
    subtitle: 'Wireless earbuds · ANC · White',
    description: 'Small details, more listening. A single set of white Nothing Ear earbuds.',
    attributes: {
      Model: 'Ear (2024)',
      Color: 'White',
      Condition: 'New',
      Pack: '1',
      Connectivity: 'Bluetooth',
      Type: 'In-ear',
      Battery: 'Up to 40.5 hours with case',
    },
    basePrice: 899900,
    accent: '#e0e0da',
  },
];
